open module com.mastfrog.acteur.server.sent.events {
// Generated by com.dv.sourcetreetool.impl.App

    exports com.mastfrog.acteur.sse;
    requires transitive com.mastfrog.acteur;
    requires transitive com.mastfrog.giulius.tests;
    requires transitive com.mastfrog.netty.http.test.harness;

    // derived from junit/junit-4.13.2 in junit/junit/4.13.2/junit-4.13.2.pom
    requires transitive junit.junit;

}
