open module com.mastfrog.acteur.mongo.async {
// Generated by com.dv.sourcetreetool.impl.App

    exports com.mastfrog.acteur.mongo.async;
    requires transitive com.mastfrog.acteur;
    requires transitive com.mastfrog.function;
    requires transitive com.mastfrog.giulius.mongodb.async;
    requires transitive com.mastfrog.giulius.tests;
    requires transitive com.mastfrog.jackson;
    requires transitive com.mastfrog.jackson.mongodb;
    requires transitive com.mastfrog.netty.http.test.harness;

    // derived from junit/junit-4.13.2 in junit/junit/4.13.2/junit-4.13.2.pom
    requires transitive junit.junit;

}
