package com.mastfrog.acteur.annotations;

import com.mastfrog.acteur.Application;
import com.mastfrog.acteur.ImplicitBindings;
import com.mastfrog.acteur.Page;
import java.util.Arrays;
import java.util.Collections;
import java.util.HashSet;
import java.util.Set;

/**
 * An application which looks up its pages using registry files on the
 * classpath, generated by an annotation processor which processes
 * &#064;HttpCall annotations.
 *
 * @author Tim Boudreau
 */
public class GenericApplication extends Application {

    public GenericApplication() {
        // Even though the varags version is semantically identical, Guice will
        // attempt to inject a Class[] into it and fail
        this(new Class<?>[0]);
    }
    
    public GenericApplication(Class<?>... excludePages) {
        Set<Class<?>> excluded = new HashSet<>(Arrays.asList(excludePages));
        ImplicitBindings implicit = getClass().getAnnotation(ImplicitBindings.class);
        Set<Class<?>> alreadyBound = implicit == null ? Collections.<Class<?>>emptySet()
                : new HashSet<>(Arrays.asList(implicit.value()));
        for (Class<? extends Page> pageType : new HttpCallRegistryLoader(getClass())) {
            if (!alreadyBound.contains(pageType) && !excluded.contains(pageType)) {
                add(pageType);
            }
        }
    }
}
