package com.mastfrog.acteur.annotations;

import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

/**
 * Mark a Page or Acteur class as being something which GenericApplication should
 * automatically find and add to itself as an HTTP endpoint.  This annotation
 * can be applied to Page classes and GenericApplication will simply load the
 * class and call <code>add(theType)</code> on itself in its constructor.  If
 * this annotation is supplied to subtypes of Acteur, then a Page subtype is
 * generated by the annotation processor, and that is what will be looked up.
 *
 * @author Tim Boudreau
 */
@Retention(RetentionPolicy.RUNTIME)
@Target(ElementType.TYPE)
public @interface HttpCall {
    public static final String META_INF_PATH = "META-INF/http/pages.list";
    int order() default 0;
    Class<?>[] scopeTypes() default {};
}
