open module com.mastfrog.marshaller.registry {
// Generated by com.dv.sourcetreetool.impl.App

    exports com.mastfrog.marshallers;
    exports com.mastfrog.marshallers.netty;

    // derived from com.fasterxml.jackson.core/jackson-databind-2.13.2.2 in com/fasterxml/jackson/core/jackson-databind/2.13.2.2/jackson-databind-2.13.2.2.pom
    requires transitive com.fasterxml.jackson.databind;

    // derived from com.google.guava/guava-31.1-jre in com/google/guava/guava/31.1-jre/guava-31.1-jre.pom
    requires transitive com.google.guava.guava;
    requires transitive com.mastfrog.util.collections;
    requires transitive com.mastfrog.util.preconditions;

    // derived from io.netty/netty-buffer-4.1.76.Final in io/netty/netty-buffer/4.1.76.Final/netty-buffer-4.1.76.Final.pom
    requires transitive io.netty.netty.buffer;
    requires java.desktop;

    // derived from junit/junit-4.13.2 in junit/junit/4.13.2/junit-4.13.2.pom
    requires transitive junit.junit;

}
