open module com.mastfrog.acteur.util {
// Generated by com.dv.sourcetreetool.impl.App

    exports com.mastfrog.acteur.util;
    requires transitive com.mastfrog.giulius.settings;
    requires transitive com.mastfrog.giulius.tests;
    requires transitive com.mastfrog.util.time;
    requires java.logging;

    // derived from javax.inject/javax.inject-1 in javax/inject/javax.inject/1/javax.inject-1.pom
    requires transitive javax.inject.javax.inject;

    // derived from junit/junit-4.13.2 in junit/junit/4.13.2/junit-4.13.2.pom
    requires transitive junit.junit;

}
