open module com.mastfrog.acteur.headers {
// Generated by com.dv.sourcetreetool.impl.App

    exports com.mastfrog.acteur.headers;

    // derived from com.google.guava/guava-31.1-jre in com/google/guava/guava/31.1-jre/guava-31.1-jre.pom
    requires transitive com.google.guava.guava;
    requires transitive com.mastfrog.acteur.util;
    requires transitive com.mastfrog.util.collections;

    // derived from io.netty/netty-codec-http-4.1.76.Final in io/netty/netty-codec-http/4.1.76.Final/netty-codec-http-4.1.76.Final.pom
    requires transitive io.netty.netty.codec.http;
    requires java.logging;

    // derived from junit/junit-4.13.2 in junit/junit/4.13.2/junit-4.13.2.pom
    requires transitive junit.junit;

}
