// Generated by com.dv.sourcetreetool.impl.App
open module com.mastfrog.url {
    exports com.mastfrog.url;
    exports com.mastfrog.util.builder;

    // Inferred from source scan

    // Sibling com.mastfrog/util-collections-3.0.0-dev
    requires com.mastfrog.collections;

    // Inferred from source scan

    // Sibling com.mastfrog/function-3.0.0-dev
    requires com.mastfrog.function;

    // Inferred from source scan
    requires com.mastfrog.preconditions;

    // Inferred from source scan

    // Sibling com.mastfrog/util-strings-3.0.0-dev
    requires com.mastfrog.strings;

    // Inferred from source scan

    // Sibling com.mastfrog/util-function-3.0.0-dev
    requires com.mastfrog.util.function;

    // Inferred from test-source-scan
    requires junit;

    // derived from com.mastfrog/simplevalidation-1.14 in com/mastfrog/simplevalidation/1.14/simplevalidation-1.14.pom
    requires simplevalidation;

}
