// Generated by com.dv.sourcetreetool.impl.App
open module com.mastfrog.acteur.jdbc {
    exports com.mastfrog.acteur.jdbc;

    // Sibling com.mastfrog/acteur-3.0.0-dev
    requires com.mastfrog.acteur;

    // Sibling com.mastfrog/injection-reflection-indexer-3.0.0-dev:compile
    requires static com.mastfrog.injection.reflection.indexer;

    // Inferred from source scan
    requires com.mastfrog.preconditions;
    requires java.sql;

}
