open module com.mastfrog.acteur.jdbc {
// Generated by com.dv.sourcetreetool.impl.App

    exports com.mastfrog.acteur.jdbc;
    requires transitive com.mastfrog.acteur;
    requires transitive com.mastfrog.injection.reflection.indexer;
    requires java.sql;

}
