// Generated by com.dv.sourcetreetool.impl.App
open module com.mastfrog.acteur.util {
    exports com.mastfrog.acteur.util;

    // Sibling com.mastfrog/giulius-settings-3.0.0-dev
    requires com.mastfrog.giulius.settings;

    // Inferred from source scan
    requires com.mastfrog.preconditions;

    // Inferred from source scan
    requires com.mastfrog.strings;

    // Sibling com.mastfrog/util-time-3.0.0-dev
    requires com.mastfrog.time;
    requires java.logging;

    // derived from javax.inject/javax.inject-1 in javax/inject/javax.inject/1/javax.inject-1.pom
    requires javax.inject;

    // Inferred from test-source-scan
    requires junit;

    requires com.mastfrog.giulius.tests;
}
