open module com.mastfrog.acteur.mongo {
// Generated by com.dv.sourcetreetool.impl.App

    exports com.mastfrog.acteur.mongo;
    exports com.mastfrog.acteur.mongo.util;
    requires transitive com.mastfrog.acteur;
    requires transitive com.mastfrog.giulius;
    requires transitive com.mastfrog.giulius.mongodb;
    requires transitive com.mastfrog.giulius.tests;
    requires transitive com.mastfrog.jackson;
    requires transitive com.mastfrog.jackson.mongodb;

    // derived from junit/junit-4.13.2 in junit/junit/4.13.2/junit-4.13.2.pom
    requires transitive junit.junit;

    // derived from org.mongodb/mongo-java-driver-3.12.11 in org/mongodb/mongo-java-driver/3.12.11/mongo-java-driver-3.12.11.pom
    requires transitive org.mongodb.mongo.java.driver;

}
