open module com.mastfrog.acteur.headers.jodatime {
// Generated by com.dv.sourcetreetool.impl.App

    exports com.mastfrog.acteur.headers.jodatime;
    requires transitive com.mastfrog.acteur.headers;
    requires transitive com.mastfrog.acteur.util;
    requires java.logging;

    // derived from joda-time/joda-time-2.10.14 in joda-time/joda-time/2.10.14/joda-time-2.10.14.pom
    requires transitive joda.time.joda.time;

}
