// Generated by com.dv.sourcetreetool.impl.App
open module com.mastfrog.acteur.headers.jodatime {
    exports com.mastfrog.acteur.headers.jodatime;

    // Sibling com.mastfrog/acteur-headers-3.0.0-dev
    requires com.mastfrog.acteur.headers;

    // Sibling com.mastfrog/acteur-util-3.0.0-dev

    // Transitive detected by source scan
    requires com.mastfrog.acteur.util;

    // Inferred from source scan
    requires com.mastfrog.strings;
    requires java.logging;

    // derived from joda-time/joda-time-2.10.14 in joda-time/joda-time/2.10.14/joda-time-2.10.14.pom
    requires transitive org.joda.time;

}
