open module com.mastfrog.acteur.annotation.processors {
// Generated by com.dv.sourcetreetool.impl.App

    exports com.mastfrog.acteur.annotation.processors;
    requires transitive com.mastfrog.annotation.processors;
    requires transitive com.mastfrog.annotation.tools;
    requires transitive com.mastfrog.function;
    requires transitive com.mastfrog.java.vogon;
    requires java.compiler;
    requires java.logging;

}
