// Generated by com.dv.sourcetreetool.impl.App
open module com.mastfrog.acteur.annotation.processors {
    exports com.mastfrog.acteur.annotation.processors;

    // Sibling com.mastfrog/annotation-processors-3.0.0-dev
    requires com.mastfrog.annotation.processors;

    // Sibling com.mastfrog/annotation-tools-3.0.0-dev
    requires com.mastfrog.annotation.tools;

    // Inferred from source scan

    // Sibling com.mastfrog/function-3.0.0-dev
    requires com.mastfrog.function;

    // Sibling com.mastfrog/java-vogon-3.0.0-dev
    requires com.mastfrog.java.vogon;
    requires java.compiler;
    requires java.logging;
    provides javax.annotation.processing.Processor with
       com.mastfrog.acteur.annotation.processors.GuiceModuleAnnotationProcessor,
       com.mastfrog.acteur.annotation.processors.HttpCallAnnotationProcessor;

}
