// Generated by com.dv.sourcetreetool.impl.App
open module com.mastfrog.acteur.headers {
    exports com.mastfrog.acteur.headers;

    // derived from com.google.guava/guava-31.1-jre in com/google/guava/guava/31.1-jre/guava-31.1-jre.pom
    requires com.google.common;

    // Sibling com.mastfrog/acteur-util-3.0.0-dev

    // Transitive detected by source scan
    requires com.mastfrog.acteur.util;

    // Inferred from source scan

    // Sibling com.mastfrog/util-collections-3.0.0-dev
    requires com.mastfrog.collections;

    // Inferred from source scan
    requires com.mastfrog.preconditions;

    // Inferred from source scan
    requires com.mastfrog.strings;

    // Inferred from source scan
    requires com.mastfrog.time;

    // derived from io.netty/netty-codec-http-0.0.0-? in io/netty/netty-codec-http/4.1.76.Final/netty-codec-http-4.1.76.Final.pom
    requires io.netty.codec.http;
    requires io.netty.common;
    requires io.netty.codec;
    requires io.netty.handler;
    requires io.netty.resolver;
    requires io.netty.transport;
    requires java.logging;

    // Inferred from test-source-scan
    requires junit;

}
