open module com.mastfrog.netty.websocket.pubsub {
// Generated by com.dv.sourcetreetool.impl.App

    exports com.mastfrog.acteur.pubsub;
    requires transitive com.mastfrog.giulius;
    requires transitive com.mastfrog.marshaller.registry;

    // derived from io.netty/netty-codec-http-4.1.76.Final in io/netty/netty-codec-http/4.1.76.Final/netty-codec-http-4.1.76.Final.pom
    requires transitive io.netty.netty.codec.http;

    // derived from junit/junit-4.13.2 in junit/junit/4.13.2/junit-4.13.2.pom
    requires transitive junit.junit;

}
