// Generated by com.dv.sourcetreetool.impl.App
open module com.mastfrog.marshaller.registry {
    exports com.mastfrog.marshallers;
    exports com.mastfrog.marshallers.netty;

    // derived from com.google.guava/guava-31.1-jre in com/google/guava/guava/31.1-jre/guava-31.1-jre.pom
    requires com.google.common;

    // Sibling com.mastfrog/util-collections-3.0.0-dev
    requires com.mastfrog.collections;

    // Inferred from source scan

    // Sibling com.mastfrog/util-preconditions-3.0.0-dev
    requires com.mastfrog.preconditions;

    // derived from io.netty/netty-buffer-0.0.0-? in io/netty/netty-buffer/4.1.76.Final/netty-buffer-4.1.76.Final.pom
    requires io.netty.buffer;

    // derived from com.fasterxml.jackson.core/jackson-databind-0.0.0-? in com/fasterxml/jackson/core/jackson-databind/2.9.9.3/jackson-databind-2.9.9.3.pom
    requires transitive com.fasterxml.jackson.databind;
    requires java.desktop;

    // Inferred from test-source-scan
    requires junit;
}
