// Generated by com.dv.sourcetreetool.impl.App
open module com.mastfrog.acteur.mongo.async {
    exports com.mastfrog.acteur.mongo.async;

    // Sibling com.mastfrog/acteur-3.0.0-dev
    requires com.mastfrog.acteur;
    requires com.mastfrog.acteur.base;
    requires com.mastfrog.acteur.headers;
    requires com.mastfrog.acteur.util;
    requires com.mastfrog.scopes;

//    // Transitive detected by source scan
//    requires com.mastfrog.acteur.deprecated;

    // Inferred from source scan
    requires com.mastfrog.collections;

    // Sibling com.mastfrog/function-3.0.0-dev
    requires com.mastfrog.function;

    // Sibling com.mastfrog/giulius-mongodb-async-3.0.0-dev
    requires com.mastfrog.giulius.mongodb.async;

    // Sibling com.mastfrog/jackson-3.0.0-dev
    requires com.mastfrog.jackson;

    // Inferred from source scan
    requires com.mastfrog.misc;

    // Inferred from source scan
    requires com.mastfrog.preconditions;

    // Inferred from source scan
    requires com.mastfrog.streams;

    // Inferred from source scan
    requires com.mastfrog.strings;

    // Inferred from source scan
    requires com.mastfrog.time;

    // Inferred from test-source-scan
    requires junit;
    provides com.mastfrog.jackson.JacksonConfigurer with
       com.mastfrog.acteur.mongo.async.ObjectIdToJSONConfigurer;

}
