// Generated by com.dv.sourcetreetool.impl.App
open module com.mastfrog.acteur.base {
    exports com.mastfrog.acteurbase;
    exports com.mastfrog.acteurbase.impl;

    requires com.mastfrog.acteur.headers;

    // Inferred from source scan
    requires com.mastfrog.collections;

    // Sibling com.mastfrog/giulius-3.0.0-dev
    requires com.mastfrog.giulius;

    // Inferred from source scan
    requires com.mastfrog.preconditions;

    // Sibling com.mastfrog/scopes-3.0.0-dev

    // Transitive detected by source scan
    requires com.mastfrog.scopes;

    // Inferred from source scan
    requires com.mastfrog.strings;

    // Inferred from source scan
    requires com.mastfrog.util.function;
    requires javax.inject;

    // Inferred from test-source-scan
    requires junit;
}
