// Generated by com.dv.sourcetreetool.impl.App
open module com.mastfrog.acteur.cookie.auth {
    exports com.mastfrog.acteur.cookie.auth;

    // Sibling com.mastfrog/acteur-3.0.0-dev
    requires com.mastfrog.acteur;
    requires com.mastfrog.acteur.headers;
    requires com.mastfrog.giulius;
    requires com.mastfrog.giulius.settings;
    requires com.mastfrog.scopes;

    // Inferred from source scan
    requires com.mastfrog.preconditions;

    // Inferred from source scan
    requires com.mastfrog.strings;
}
