open module com.mastfrog.acteur.base {
// Generated by com.dv.sourcetreetool.impl.App

    exports com.mastfrog.acteurbase;
    requires transitive com.mastfrog.acteur.headers;
    requires transitive com.mastfrog.giulius;
    requires transitive com.mastfrog.scopes;

    // derived from junit/junit-4.13.2 in junit/junit/4.13.2/junit-4.13.2.pom
    requires transitive junit.junit;

}
