open module com.mastfrog.acteur.deprecated {
// Generated by com.dv.sourcetreetool.impl.App

    exports com.mastfrog.acteur;
    exports com.mastfrog.acteur.io;
    requires transitive com.mastfrog.acteur;
    requires transitive com.mastfrog.acteur.headers;

    // derived from commons-codec/commons-codec-1.15 in commons-codec/commons-codec/1.15/commons-codec-1.15.pom
    requires transitive commons.codec.commons.codec;
    requires java.logging;

    // derived from junit/junit-4.13.2 in junit/junit/4.13.2/junit-4.13.2.pom
    requires transitive junit.junit;

}
