open module com.mastfrog.url {
// Generated by com.dv.sourcetreetool.impl.App

    exports com.mastfrog.url;
    exports com.mastfrog.util.builder;
    requires transitive com.mastfrog.function;

    // derived from com.mastfrog/simplevalidation-1.14 in com/mastfrog/simplevalidation/1.14/simplevalidation-1.14.pom
    requires transitive com.mastfrog.simplevalidation;
    requires transitive com.mastfrog.util.collections;
    requires transitive com.mastfrog.util.function;
    requires transitive com.mastfrog.util.strings;

    // derived from junit/junit-4.13.2 in junit/junit/4.13.2/junit-4.13.2.pom
    requires transitive junit.junit;

}
