// Generated by com.dv.sourcetreetool.impl.App
open module com.mastfrog.acteur {
    exports com.mastfrog.acteur;
    exports com.mastfrog.acteur.annos;
    exports com.mastfrog.acteur.auth;
    exports com.mastfrog.acteur.debug;
    exports com.mastfrog.acteur.errors;
    exports com.mastfrog.acteur.preconditions;
    exports com.mastfrog.acteur.server;
    exports com.mastfrog.acteur.spi;
    exports com.mastfrog.acteur.websocket;

    requires static com.mastfrog.injection.reflection.indexer;
    // Sibling com.mastfrog/acteur-annotations-3.0.0-dev:compile
    requires com.mastfrog.acteur.annotations;

    // Sibling com.mastfrog/acteur-base-3.0.0-dev
    requires com.mastfrog.acteur.base;

    // Sibling com.mastfrog/acteur-headers-3.0.0-dev
    requires com.mastfrog.acteur.headers;

    // Sibling com.mastfrog/acteur-util-3.0.0-dev
    requires com.mastfrog.acteur.util;

    // Sibling com.mastfrog/annotation-processors-3.0.0-dev:compile
    requires com.mastfrog.annotation.processors;

    // Inferred from source scan
    requires com.mastfrog.collections;

    // Inferred from source scan

    // Sibling com.mastfrog/function-3.0.0-dev
    requires com.mastfrog.function;

    // Sibling com.mastfrog/giulius-3.0.0-dev
    requires com.mastfrog.giulius;

    // Transitive detected by source scan
    requires com.mastfrog.giulius.annotations;
    requires com.mastfrog.giulius.annotation.processors;
    requires com.mastfrog.giulius.settings;
    requires com.mastfrog.giulius.tests;

    // Sibling com.mastfrog/giulius-threadpool-3.0.0-dev
    requires com.mastfrog.giulius.threadpool;

    // Sibling com.mastfrog/marshaller-registry-3.0.0-dev
    requires com.mastfrog.marshaller.registry;
    
    requires com.mastfrog.netty.http.client;
    requires com.mastfrog.netty.http.test.harness;

    // Inferred from source scan
    // Sibling com.mastfrog/util-misc-3.0.0-dev
    requires com.mastfrog.misc;

    // Inferred from source scan
    requires com.mastfrog.net;

    // Inferred from source scan
    requires com.mastfrog.preconditions;

    // Sibling com.mastfrog/scopes-3.0.0-dev
    requires com.mastfrog.scopes;

    // Inferred from source scan
    requires com.mastfrog.streams;

    // Inferred from source scan
    requires com.mastfrog.strings;

    // Inferred from source scan
    requires com.mastfrog.time;

    // Sibling com.mastfrog/url-3.0.0-dev
    requires com.mastfrog.url;

    // Inferred from source scan
    requires com.mastfrog.util.function;

    // derived from io.netty/netty-buffer-0.0.0-? in io/netty/netty-buffer/4.1.76.Final/netty-buffer-4.1.76.Final.pom
    requires io.netty.buffer;

    // derived from io.netty/netty-handler-0.0.0-? in io/netty/netty-handler/4.1.76.Final/netty-handler-4.1.76.Final.pom
    requires io.netty.handler;

    // derived from com.fasterxml.jackson.core/jackson-databind-0.0.0-? in com/fasterxml/jackson/core/jackson-databind/2.9.9.3/jackson-databind-2.9.9.3.pom
    requires transitive com.fasterxml.jackson.databind;
    requires java.logging;

    // derived from org.javassist/javassist-3.28.0-GA in org/javassist/javassist/3.28.0-GA/javassist-3.28.0-GA.pom
    requires javassist;

    // Inferred from test-source-scan
    requires junit;

}
