open module com.mastfrog.acteur {
// Generated by com.dv.sourcetreetool.impl.App

    exports com.mastfrog.acteur;
    exports com.mastfrog.acteur.annotations;
    exports com.mastfrog.acteur.auth;
    exports com.mastfrog.acteur.debug;
    exports com.mastfrog.acteur.errors;
    exports com.mastfrog.acteur.preconditions;
    exports com.mastfrog.acteur.server;
    exports com.mastfrog.acteur.spi;
    exports com.mastfrog.acteur.websocket;

    // derived from com.fasterxml.jackson.core/jackson-databind-2.13.2.2 in com/fasterxml/jackson/core/jackson-databind/2.13.2.2/jackson-databind-2.13.2.2.pom
    requires transitive com.fasterxml.jackson.databind;
    requires transitive com.mastfrog.acteur.annotations;
    requires transitive com.mastfrog.acteur.base;
    requires transitive com.mastfrog.acteur.headers;
    requires transitive com.mastfrog.acteur.util;
    requires transitive com.mastfrog.annotation.processors;
    requires transitive com.mastfrog.function;
    requires transitive com.mastfrog.giulius;
    requires transitive com.mastfrog.giulius.tests;
    requires transitive com.mastfrog.giulius.threadpool;
    requires transitive com.mastfrog.marshaller.registry;
    requires transitive com.mastfrog.netty.http.client;
    requires transitive com.mastfrog.netty.http.test.harness;
    requires transitive com.mastfrog.scopes;
    requires transitive com.mastfrog.url;
    requires transitive com.mastfrog.util.misc;

    // derived from io.netty/netty-buffer-4.1.76.Final in io/netty/netty-buffer/4.1.76.Final/netty-buffer-4.1.76.Final.pom
    requires transitive io.netty.netty.buffer;

    // derived from io.netty/netty-handler-4.1.76.Final in io/netty/netty-handler/4.1.76.Final/netty-handler-4.1.76.Final.pom
    requires transitive io.netty.netty.handler;
    requires java.logging;

    // derived from junit/junit-4.13.2 in junit/junit/4.13.2/junit-4.13.2.pom
    requires transitive junit.junit;

    // derived from org.bouncycastle/bcpkix-jdk15on-1.70 in org/bouncycastle/bcpkix-jdk15on/1.70/bcpkix-jdk15on-1.70.pom
    requires transitive org.bouncycastle.pkix;

    // derived from org.javassist/javassist-3.28.0-GA in org/javassist/javassist/3.28.0-GA/javassist-3.28.0-GA.pom
    requires transitive org.javassist.javassist;

}
