open module com.mastfrog.acteur.resources {
// Generated by com.dv.sourcetreetool.impl.App

    exports com.mastfrog.acteur.resources;
    exports com.mastfrog.acteur.resources.markup;

    // derived from com.jcraft/jzlib-1.1.3 in com/jcraft/jzlib/1.1.3/jzlib-1.1.3.pom
    requires transitive com.jcraft.jzlib;
    requires transitive com.mastfrog.acteur;
    requires transitive com.mastfrog.giulius.tests;
    requires transitive com.mastfrog.netty.http.client;
    requires transitive com.mastfrog.netty.http.test.harness;

    // derived from io.netty/netty-buffer-4.1.76.Final in io/netty/netty-buffer/4.1.76.Final/netty-buffer-4.1.76.Final.pom
    requires transitive io.netty.netty.buffer;

    // derived from junit/junit-4.13.2 in junit/junit/4.13.2/junit-4.13.2.pom
    requires transitive junit.junit;

    // derived from org.xeustechnologies/jtar-1.1 in org/xeustechnologies/jtar/1.1/jtar-1.1.pom
    requires transitive org.xeustechnologies.jtar;

}
